// Package walker discovers source files in a directory tree.
package walker

import (
	"bufio"
	"os"
	"path/filepath"
	"strings"

	"github.com/harneet2512/groundtruth/gt-index/internal/specs"
)

// skipDirs are directories to always skip.
var skipDirs = map[string]bool{
	".git":          true,
	"__pycache__":   true,
	"node_modules":  true,
	".tox":          true,
	".eggs":         true,
	".venv":         true,
	"venv":          true,
	".mypy_cache":   true,
	"dist":          true,
	"build":         true,
	".next":         true,
	"vendor":        true, // Go vendor — can optionally include
	"target":        true, // Rust/Java build output
	"gen":           true, // Generated code (protobuf, gRPC)
	"generated":     true,
	"__generated__": true,
	"_generated":    true,
}

// SourceFile represents a discovered source file.
type SourceFile struct {
	Path     string // relative path from root
	AbsPath  string
	Language string
	Spec     *specs.Spec
}

// WalkResult contains discovered files and metadata about the walk.
type WalkResult struct {
	Files        []SourceFile
	FilesSkipped int // number of files beyond maxFiles that were not indexed
}

// Walk discovers all source files under root that have a registered language spec.
// Respects .gitignore patterns (basic implementation).
func Walk(root string, maxFiles int) ([]SourceFile, error) {
	result, err := WalkWithMeta(root, maxFiles)
	return result.Files, err
}

// WalkWithMeta is like Walk but also returns metadata (files skipped count).
func WalkWithMeta(root string, maxFiles int) (WalkResult, error) {
	root, _ = filepath.Abs(root)

	// Load .gitignore patterns
	ignorePatterns := loadGitignore(filepath.Join(root, ".gitignore"))

	var files []SourceFile
	skipped := 0
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil // skip errors
		}
		if len(files) >= maxFiles {
			if !info.IsDir() && specs.ForExtension(filepath.Ext(path)) != nil {
				skipped++
			}
			if skipped > 1000 {
				return filepath.SkipAll // stop counting after 1000 to save time
			}
			return nil
		}

		// Skip hidden and known directories
		if info.IsDir() {
			base := filepath.Base(path)
			if skipDirs[base] || strings.HasPrefix(base, ".") {
				return filepath.SkipDir
			}
			return nil
		}

		// Skip large files (>500KB)
		if info.Size() > 500*1024 {
			return nil
		}

		// Check if file has a registered language spec
		ext := filepath.Ext(path)
		spec := specs.ForExtension(ext)
		if spec == nil {
			return nil
		}

		relPath, _ := filepath.Rel(root, path)
		relPath = filepath.ToSlash(relPath)

		// Check gitignore
		if isIgnored(relPath, ignorePatterns) {
			return nil
		}

		// Skip generated files (check first line for codegen markers)
		if isGeneratedFile(path) {
			return nil
		}

		files = append(files, SourceFile{
			Path:     relPath,
			AbsPath:  path,
			Language: spec.Name,
			Spec:     spec,
		})
		return nil
	})

	return WalkResult{Files: files, FilesSkipped: skipped}, err
}

// isGeneratedFile checks the first line of a file for common codegen markers.
func isGeneratedFile(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()
	scanner := bufio.NewScanner(f)
	// Check first 3 lines for generated markers
	for i := 0; i < 3 && scanner.Scan(); i++ {
		line := scanner.Text()
		if strings.Contains(line, "Code generated") ||
			strings.Contains(line, "Generated by") ||
			strings.Contains(line, "DO NOT EDIT") ||
			strings.Contains(line, "AUTO-GENERATED") ||
			strings.Contains(line, "auto-generated") {
			return true
		}
	}
	return false
}

func loadGitignore(path string) []string {
	f, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer f.Close()

	var patterns []string
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		patterns = append(patterns, line)
	}
	return patterns
}

func isIgnored(relPath string, patterns []string) bool {
	base := filepath.Base(relPath)
	for _, p := range patterns {
		// Glob matching against basename
		if matched, _ := filepath.Match(p, base); matched {
			return true
		}
		// Directory-level matching: pattern matches a directory component
		// e.g. "vendor" matches "vendor/foo.go" but NOT "foo_vendor.go"
		// e.g. "_test" matches "_test/foo.go" but NOT "foo_test.go"
		if strings.Contains(p, "/") {
			// Path pattern: match against full relative path
			if matched, _ := filepath.Match(p, relPath); matched {
				return true
			}
		} else {
			// Simple name: match as directory component only
			dirPart := "/" + filepath.ToSlash(relPath) + "/"
			if strings.Contains(dirPart, "/"+p+"/") {
				return true
			}
		}
	}
	return false
}

// IsTestFile checks if a file path is a test file based on conventions.
func IsTestFile(relPath string) bool {
	base := filepath.Base(relPath)
	dir := filepath.ToSlash(filepath.Dir(relPath))
	ext := filepath.Ext(base)
	stem := strings.TrimSuffix(base, ext)

	// Python: test_*.py, *_test.py
	if strings.HasPrefix(base, "test_") || strings.HasSuffix(stem, "_test") {
		return true
	}
	// Go: *_test.go
	if strings.HasSuffix(base, "_test.go") {
		return true
	}
	// JS/TS: *.test.js, *.spec.js, *.test.ts, *.spec.ts
	if strings.Contains(base, ".test.") || strings.Contains(base, ".spec.") {
		return true
	}
	// JVM (Java/Kotlin/Scala/Groovy): *Test.java, *Tests.java, *Test.kt, etc.
	if strings.HasSuffix(stem, "Test") || strings.HasSuffix(stem, "Tests") || strings.HasSuffix(stem, "Spec") {
		switch ext {
		case ".java", ".kt", ".kts", ".scala", ".groovy":
			return true
		}
	}
	// C#: *Test.cs, *Tests.cs
	if (strings.HasSuffix(stem, "Test") || strings.HasSuffix(stem, "Tests")) && ext == ".cs" {
		return true
	}
	// PHP: *Test.php (PHPUnit convention)
	if strings.HasSuffix(stem, "Test") && ext == ".php" {
		return true
	}
	// Swift: *Tests.swift
	if (strings.HasSuffix(stem, "Tests") || strings.HasSuffix(stem, "Test")) && ext == ".swift" {
		return true
	}
	// Ruby: *_spec.rb (RSpec convention)
	if strings.HasSuffix(stem, "_spec") && ext == ".rb" {
		return true
	}
	// Directory-based: tests/, __tests__/, test/, spec/ (all languages)
	// Use path-segment-aware checks to avoid false positives like "contests/" or "attestations/"
	if containsPathSegment(dir, "tests") || strings.Contains(dir, "__tests__") || containsPathSegment(dir, "test") || containsPathSegment(dir, "spec") {
		return true
	}
	// JVM convention: src/test/ directory
	if strings.Contains(dir, "src/test/") {
		return true
	}
	return false
}

// containsPathSegment checks if dir contains segment as a complete path component.
// dir is expected to use forward slashes (from filepath.ToSlash).
// Matches: "tests/foo", "foo/tests/bar", "foo/tests", and bare "tests".
func containsPathSegment(dir, segment string) bool {
	if dir == segment {
		return true
	}
	if strings.HasPrefix(dir, segment+"/") {
		return true
	}
	if strings.HasSuffix(dir, "/"+segment) {
		return true
	}
	return strings.Contains(dir, "/"+segment+"/")
}
