"""GT Telemetry — structured observability for provable layer utilization."""

from .schemas import (
    GTLayerEvent,
    GTAgentReactionEvent,
    GTBeliefEvent,
    EvidenceItem,
    EvidenceKind,
    get_iteration_band,
)
from .writer import GTTelemetryWriter
from .evidence import make_evidence_item, truncate_evidence_by_priority
from .constants import (
    SCHEMA_VERSION,
    L3_POST_EDIT_TOKEN_CAP,
    L3_POST_FAILURE_TOKEN_CAP,
    L3_LATE_REPAIR_TOKEN_CAP,
    L3B_LATE_TOKEN_CAP,
    L4_TOKEN_CAP,
    L5B_TOKEN_CAP,
    BAND_EARLY,
    BAND_MID,
    BAND_LATE,
    BAND_FINAL,
    L3B_EDGE_LIMITS,
    L3B_BROAD_NAV_CUTOFF_RATIO,
    VK_TARGETED_SYMBOL,
    VK_TARGETED_FILE,
    VK_TARGETED_RELATED,
    VK_BROAD,
    VK_IRRELEVANT,
    VK_UNKNOWN,
    VALID_LAYERS,
    VALID_VERIFICATION_KINDS,
    VALID_FOLLOW_TYPES,
    VALID_BELIEF_STATUSES,
)

__all__ = [
    "GTLayerEvent",
    "GTAgentReactionEvent",
    "GTBeliefEvent",
    "EvidenceItem",
    "EvidenceKind",
    "GTTelemetryWriter",
    "get_iteration_band",
    "make_evidence_item",
    "truncate_evidence_by_priority",
    "SCHEMA_VERSION",
    "L3_POST_EDIT_TOKEN_CAP",
    "L3_POST_FAILURE_TOKEN_CAP",
    "L3_LATE_REPAIR_TOKEN_CAP",
    "L3B_LATE_TOKEN_CAP",
    "L4_TOKEN_CAP",
    "L5B_TOKEN_CAP",
    "BAND_EARLY",
    "BAND_MID",
    "BAND_LATE",
    "BAND_FINAL",
    "L3B_EDGE_LIMITS",
    "L3B_BROAD_NAV_CUTOFF_RATIO",
    "VK_TARGETED_SYMBOL",
    "VK_TARGETED_FILE",
    "VK_TARGETED_RELATED",
    "VK_BROAD",
    "VK_IRRELEVANT",
    "VK_UNKNOWN",
    "VALID_LAYERS",
    "VALID_VERIFICATION_KINDS",
    "VALID_FOLLOW_TYPES",
    "VALID_BELIEF_STATUSES",
]
